version: '3'
services:
  importer:
    env_file: '.env'
    image: 'importer'
    container_name: 'importer'
    networks:
      - backend
  database:
    env_file: '.env'
    image: 'mongo'
    container_name: 'buttonstorage'
    environment:
      - MONGO_INITDB_DATABASE=${DBNAME}
      - MONGO_INITDB_ROOT_USERNAME=${DBUSER}
      - MONGO_INITDB_ROOT_PASSWORD=${DBPWD}
    volumes:
      - ./database/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./database/mongo-volume:/data/db
    ports:
      - '27017-27019:27017-27019'
    networks:
      - backend
  backend:
    env_file: '.env'
    image: 'backend'
    container_name: 'backend'
    ports:
      - '${BACKEND_PORT}:${BACKEND_PORT}'
    networks:
      - backend

networks:
  backend:
    driver: 'bridge'
